"""阶段0 全部数据表

Revision ID: b790765f04da
Revises: 
Create Date: 2026-07-27 16:45:30.070229

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b790765f04da'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_run_agent_role'), ['agent_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_run_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_run_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_run_status'), ['status'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('world_rules', sa.JSON(), nullable=True),
    sa.Column('boundaries', sa.JSON(), nullable=True),
    sa.Column('channel_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_title'), ['title'], unique=False)

    op.create_table('approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_target_key'), ['target_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_target_type'), ['target_type'], unique=False)

    op.create_table('canon_delta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_canon_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('canon_delta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canon_delta_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_canon_delta_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canon_delta_provisional'), ['provisional'], unique=False)
        batch_op.create_index(batch_op.f('ix_canon_delta_status'), ['status'], unique=False)

    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'DRAFTING', 'ADVERSARIAL_REVIEW', 'JUDGING', 'NEEDS_REVISION', 'NEEDS_REPLAN', 'HUMAN_REVIEW', 'APPROVED', 'CANON_LOCKED', 'EXPORTED', 'STALE', name='chapterstatus'), nullable=False),
    sa.Column('revision_round', sa.Integer(), nullable=False),
    sa.Column('outline_version', sa.Integer(), nullable=False),
    sa.Column('target_words', sa.Integer(), nullable=False),
    sa.Column('built_on_provisional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_key')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_order_index'), ['order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_volume_id'), ['volume_id'], unique=False)

    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'character_id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_project_id'), ['project_id'], unique=False)

    op.create_table('character_arc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arc_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_arc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_arc_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_arc_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_arc_project_id'), ['project_id'], unique=False)

    op.create_table('draft_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lineage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision_of', sa.Integer(), nullable=True),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('locked_ranges', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outline_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['revision_of'], ['draft_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_version_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_version_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_version_lineage_id'), ['lineage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_version_project_id'), ['project_id'], unique=False)

    op.create_table('entity_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_state_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_state_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_state_provisional'), ['provisional'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_state_source_chapter'), ['source_chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_state_state_type'), ['state_type'], unique=False)

    op.create_table('plot_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planned_payoff', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'thread_id')
    )
    with op.batch_alter_table('plot_thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_thread_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_thread_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_thread_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_thread_thread_id'), ['thread_id'], unique=False)

    op.create_table('plot_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'unit_id')
    )
    with op.batch_alter_table('plot_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_unit_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_unit_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_unit_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_unit_volume_id'), ['volume_id'], unique=False)

    op.create_table('relationship_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('party_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('party_b', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'party_a', 'party_b')
    )
    with op.batch_alter_table('relationship_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_state_party_a'), ['party_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_state_party_b'), ['party_b'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_state_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_state_provisional'), ['provisional'], unique=False)

    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'scene_id')
    )
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_scene_id'), ['scene_id'], unique=False)

    op.create_table('story_kernel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version')
    )
    with op.batch_alter_table('story_kernel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_kernel_approved'), ['approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_kernel_project_id'), ['project_id'], unique=False)

    op.create_table('volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'volume_id')
    )
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volume_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volume_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_volume_volume_id'), ['volume_id'], unique=False)

    op.create_table('workflow_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_node', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_spent', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_run_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_run_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_run_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_run_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_run_status'), ['status'], unique=False)

    op.create_table('judge_verdict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_version_id', sa.Integer(), nullable=False),
    sa.Column('chapter_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['draft_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('judge_verdict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judge_verdict_chapter_key'), ['chapter_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_verdict_draft_version_id'), ['draft_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_verdict_verdict'), ['verdict'], unique=False)

    op.create_table('node_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('output_snapshot', sa.JSON(), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('budget_spent', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'attempt')
    )
    with op.batch_alter_table('node_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_run_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_run_node_name'), ['node_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_run_sub_key'), ['sub_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_run_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('review_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_version_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hard_gate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('downweighted', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['draft_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_version_id', 'issue_id')
    )
    with op.batch_alter_table('review_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_issue_draft_version_id'), ['draft_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_issue_hard_gate'), ['hard_gate'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_issue_reviewer_role'), ['reviewer_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_issue_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_issue_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_issue_status'))
        batch_op.drop_index(batch_op.f('ix_review_issue_severity'))
        batch_op.drop_index(batch_op.f('ix_review_issue_reviewer_role'))
        batch_op.drop_index(batch_op.f('ix_review_issue_hard_gate'))
        batch_op.drop_index(batch_op.f('ix_review_issue_draft_version_id'))

    op.drop_table('review_issue')
    with op.batch_alter_table('node_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_run_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_node_run_sub_key'))
        batch_op.drop_index(batch_op.f('ix_node_run_status'))
        batch_op.drop_index(batch_op.f('ix_node_run_node_name'))
        batch_op.drop_index(batch_op.f('ix_node_run_idempotency_key'))

    op.drop_table('node_run')
    with op.batch_alter_table('judge_verdict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judge_verdict_verdict'))
        batch_op.drop_index(batch_op.f('ix_judge_verdict_draft_version_id'))
        batch_op.drop_index(batch_op.f('ix_judge_verdict_chapter_key'))

    op.drop_table('judge_verdict')
    with op.batch_alter_table('workflow_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_run_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_run_project_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_run_kind'))
        batch_op.drop_index(batch_op.f('ix_workflow_run_chapter_key'))
        batch_op.drop_index(batch_op.f('ix_workflow_run_batch_id'))

    op.drop_table('workflow_run')
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volume_volume_id'))
        batch_op.drop_index(batch_op.f('ix_volume_status'))
        batch_op.drop_index(batch_op.f('ix_volume_project_id'))

    op.drop_table('volume')
    with op.batch_alter_table('story_kernel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_kernel_project_id'))
        batch_op.drop_index(batch_op.f('ix_story_kernel_approved'))

    op.drop_table('story_kernel')
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_scene_id'))
        batch_op.drop_index(batch_op.f('ix_scene_project_id'))
        batch_op.drop_index(batch_op.f('ix_scene_chapter_key'))

    op.drop_table('scene')
    with op.batch_alter_table('relationship_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_state_provisional'))
        batch_op.drop_index(batch_op.f('ix_relationship_state_project_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_state_party_b'))
        batch_op.drop_index(batch_op.f('ix_relationship_state_party_a'))

    op.drop_table('relationship_state')
    with op.batch_alter_table('plot_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_unit_volume_id'))
        batch_op.drop_index(batch_op.f('ix_plot_unit_unit_id'))
        batch_op.drop_index(batch_op.f('ix_plot_unit_status'))
        batch_op.drop_index(batch_op.f('ix_plot_unit_project_id'))

    op.drop_table('plot_unit')
    with op.batch_alter_table('plot_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_thread_thread_id'))
        batch_op.drop_index(batch_op.f('ix_plot_thread_status'))
        batch_op.drop_index(batch_op.f('ix_plot_thread_project_id'))
        batch_op.drop_index(batch_op.f('ix_plot_thread_kind'))

    op.drop_table('plot_thread')
    with op.batch_alter_table('entity_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_state_state_type'))
        batch_op.drop_index(batch_op.f('ix_entity_state_source_chapter'))
        batch_op.drop_index(batch_op.f('ix_entity_state_provisional'))
        batch_op.drop_index(batch_op.f('ix_entity_state_project_id'))
        batch_op.drop_index(batch_op.f('ix_entity_state_entity_id'))

    op.drop_table('entity_state')
    with op.batch_alter_table('draft_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_version_project_id'))
        batch_op.drop_index(batch_op.f('ix_draft_version_lineage_id'))
        batch_op.drop_index(batch_op.f('ix_draft_version_chapter_key'))
        batch_op.drop_index(batch_op.f('ix_draft_version_candidate_id'))

    op.drop_table('draft_version')
    with op.batch_alter_table('character_arc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_arc_project_id'))
        batch_op.drop_index(batch_op.f('ix_character_arc_character_id'))
        batch_op.drop_index(batch_op.f('ix_character_arc_chapter_key'))

    op.drop_table('character_arc')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_project_id'))
        batch_op.drop_index(batch_op.f('ix_character_character_id'))

    op.drop_table('character')
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_volume_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_unit_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_status'))
        batch_op.drop_index(batch_op.f('ix_chapter_project_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_order_index'))
        batch_op.drop_index(batch_op.f('ix_chapter_chapter_key'))

    op.drop_table('chapter')
    with op.batch_alter_table('canon_delta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canon_delta_status'))
        batch_op.drop_index(batch_op.f('ix_canon_delta_provisional'))
        batch_op.drop_index(batch_op.f('ix_canon_delta_project_id'))
        batch_op.drop_index(batch_op.f('ix_canon_delta_chapter_key'))

    op.drop_table('canon_delta')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_target_type'))
        batch_op.drop_index(batch_op.f('ix_approval_target_key'))
        batch_op.drop_index(batch_op.f('ix_approval_project_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decision'))

    op.drop_table('approval')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_title'))
        batch_op.drop_index(batch_op.f('ix_project_status'))

    op.drop_table('project')
    with op.batch_alter_table('model_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_run_status'))
        batch_op.drop_index(batch_op.f('ix_model_run_project_id'))
        batch_op.drop_index(batch_op.f('ix_model_run_chapter_key'))
        batch_op.drop_index(batch_op.f('ix_model_run_agent_role'))

    op.drop_table('model_run')
    # ### end Alembic commands ###
