"""SQLModel 表定义。"""

from novel_agent.domain.models.tables import (
    AnnalsCardRecord,
    ApprovalRecord,
    CanonDeltaRecord,
    ChapterRecord,
    CharacterArcRecord,
    CharacterRecord,
    ConflictRecord,
    DraftVersionRecord,
    EntityStateRecord,
    IdentityAliasRecord,
    JudgeVerdictRecord,
    ModelRunRecord,
    NodeRunRecord,
    PayoffBeatRecord,
    PlotThreadRecord,
    PlotUnitRecord,
    ProjectRecord,
    RelationshipStateRecord,
    ReviewIssueRecord,
    SceneRecord,
    StoryKernelRecord,
    StructureMapRecord,
    VolumeRecord,
    WorkflowRunRecord,
)

__all__ = [
    "AnnalsCardRecord",
    "ApprovalRecord",
    "CanonDeltaRecord",
    "ChapterRecord",
    "CharacterArcRecord",
    "CharacterRecord",
    "ConflictRecord",
    "DraftVersionRecord",
    "EntityStateRecord",
    "IdentityAliasRecord",
    "JudgeVerdictRecord",
    "ModelRunRecord",
    "NodeRunRecord",
    "PayoffBeatRecord",
    "PlotThreadRecord",
    "PlotUnitRecord",
    "ProjectRecord",
    "RelationshipStateRecord",
    "ReviewIssueRecord",
    "SceneRecord",
    "StoryKernelRecord",
    "StructureMapRecord",
    "VolumeRecord",
    "WorkflowRunRecord",
]
